<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.5.0</Version>
    <AssemblyVersion>0.7.0.0</AssemblyVersion>
    <ApplicationIcon>Resources\icon.ico</ApplicationIcon>
    <FileVersion>0.7.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\icon.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

</Project>